name: 'Danger action'
description: 'A danger action to add to your CI'
inputs:
  JiraTag:
    description: 'Your repo tag in JIRA'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'