on: [pull_request]

jobs:
  prueba:
    runs-on: ubuntu-latest
    name: 
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: danger-action-tnp
        uses: TheNeonProject/danger-action@v0.1.3
        with:
          jira-tag: 'TNP'
          eslint: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_SECRET }}