on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Prueba
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      
      - name: Trying my action
        uses: ./
        id: Probando
        with:
            JiraTag: 'Hola'